name: Update Articles

on:
  schedule:
    - cron: '0 12 * * *'  # Cada día a las 12 PM UTC
  workflow_dispatch:       # Permite ejecutar manualmente
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Instalar dependencias de Python
        run: |
          pip install selenium beautifulsoup4 webdriver-manager

      - name: Crear carpeta js si no existe
        run: mkdir -p js

      - name: Ejecutar el script de scraping
        run: python scripts/acceder_articulos.py

      - name: Subir cambios si los hay
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add js/articulos_Animales.js
          git commit -m "🔄 Actualización automática de artículos" || echo "Sin cambios"
          git push
