name: Actualizar Articulos

on: [push]

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias 
        run: |
          pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Ejecutar el script para actualizar noticias
        run: |
          xvfb-run python scripts/acceder_articulos.py

      - name: Subir cambios si los hay
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add js/articulos.js
          git commit -m "🔄 Actualización automática de noticias cada 12h" || echo "Sin cambios"
          git push
