# .github/workflows/actualizar_eventos.yml
name: Actualizar eventos naturales

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:       # También manualmente si quieres

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests

      - name: Ejecutar eventos_naturales.py
        run: python scripts/eventos_naturales.py

      - name: Subir cambios si los hay
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Actualizar automáticamente" || echo "No hay cambios"
          git push
