name: Actualizar eventos naturales en Perú

on:
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas
  workflow_dispatch:        # También puede ejecutarse manualmente

jobs:
  actualizar_eventos:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Instalar dependencias
        run: pip install requests

      - name: ▶️ Ejecutar script de eventos naturales
        run: python scripts/eventos_naturales.py

      - name: 📂 Mostrar archivos generados
        run: |
          echo "✅ Contenido generado:"
          ls -lh data/
          ls -lh js/
          echo "Vista previa del JSON:"
          head -n 20 data/eventos_naturales.json || echo "No se encontró JSON"
          echo "Vista previa del JS:"
          head -n 20 js/eventos_naturales.js || echo "No se encontró JS"

      - name: 📤 Subir cambios si los hay
        env:
          GH_TOKEN: ${{ secrets.GH_TOKN_TRABAJO_FINAL }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

          git add data/eventos_naturales.json js/eventos_naturales.js
          git commit -m "🔁 Actualización automática: eventos naturales en Perú" || echo "❌ Sin cambios"
          git push || echo "❌ No se pudo hacer push (quizá sin cambios)"
